# Generated by Django 3.2.7 on 2022-07-16 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('date_opened', models.DateTimeField()),
                ('date_closed', models.DateTimeField()),
                ('zone', models.CharField(max_length=100)),
                ('waiter', models.CharField(max_length=100)),
                ('cashier', models.CharField(max_length=100)),
                ('diners', models.IntegerField(default=0)),
                ('table', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('type_payment', models.CharField(max_length=50)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.order')),
            ],
        ),
    ]
